#!/data/data/com.termux/files/usr/bin/bash

cd ~/

echo 'command_not_found_handle() {
	/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
}' >> bash.bashrc
 
echo 'Enter Name for ASCII TEXT ART : ' |lolcat
read logo
echo "figlet $logo |lolcat" >> bash.bashrc

echo "echo 'Script Created By : Viliyam Vasava'" >> bash.bashrc

echo "echo '  COMMANDS	: DESCRIPTION'" >> bash.bashrc
echo "echo '  =============================' |lolcat -a" >> bash.bashrc

[ -d ~/metasploit-framework ] && echo "echo '  msfconsole	: Start metasploit-Framework'" >> bash.bashrc
[ -d ~/metasploit-framework ] && echo "echo '  msfvenom	: Create Android Payload'" >> bash.bashrc
[ -d ~/metasploit-framework ] && echo "echo '  paylaod	: Create Android Payload'" >> bash.bashrc
[ -d ~/metasploit-framework ] && echo "echo '  fix-ng	: Fix nokogiri Error if accured'" >> bash.bashrc

echo "echo '  ascii-art	: Change ASCII Text ART'" >> bash.bashrc
echo "echo '  easymux	: Learn more with EasyMux on Youtube'" >> bash.bashrc

echo "echo '  =============================' |lolcat -a" >> bash.bashrc

echo "PS1='┌─[\\@][\\W][\\#]\\n|\\n└─[$logo@EasyMux]\\$ ' " >> bash.bashrc


rm $PREFIX/etc/bash.bashrc
echo "" > $PREFIX/etc/motd
rm $PREFIX/etc/motd

mv bash.bashrc $PREFIX/etc/

cd ~/
[ -d ~/termux-metasploit-helper ] && rm -rf ~/termux-metasploit-helper

echo 'Congratulations setup is done...' |lolcat -a

echo 'Open New Session' |lolcat -a




