#!/data/data/com.termux/files/usr/bin/bash
termux-setup-storage

pkg install ruby -y
echo "Preparing..."
gem install lolcat

pkg install figlet -y |lolcat

chmod +x *

rm README.md

[ -d ~/metasploit-framework ] && mv msf* $PREFIX/bin
[ -d ~/metasploit-framework ] && mv payload $PREFIX/bin

mv easymux $PREFIX/bin
mv ascii-art $PREFIX/bin
mv fix-ng $PREFIX/bin

cd ~/

ascii-art







