#!/data/data/com.termux/files/usr/bin/bash

termux-setup-storage

sleep 3

pkg install ruby -y
echo "Preparing..."
gem install lolcat

pkg install figlet -y |lolcat

cd ~/

echo 'command_not_found_handle() {
	/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
}' >> bash.bashrc
 
echo 'Enter Your Name : ' |lolcat

read logo

echo "PS1='$logo@EasyMux \\$ ' " >> bash.bashrc

echo "figlet $logo |lolcat" >> bash.bashrc

echo 'echo "Script Created by : Viliyam Vasava" |lolcat -a' >> bash.bashrc
echo 'echo ""' >> bash.bashrc
[ -d ~/metasploit-framework ] && echo 'echo "To strat Metasploit type		msfconsole."' >> bash.bashrc
[ -d ~/metasploit-framework ] && echo 'echo "To create Payload type`		msfvenom or payload."' >> bash.bashrc
[ -d ~/metasploit-framework ] && echo 'echo "If problem with nokogiri type	fix-nokogiri."' >> bash.bashrc
echo 'echo ""' >> bash.bashrc
echo 'echo "Subscribe my channel & learn more type	easymux." |lolcat -a' >> bash.bashrc

rm $PREFIX/etc/bash.bashrc
echo "" > $PREFIX/etc/motd
rm $PREFIX/etc/motd

mv bash.bashrc $PREFIX/etc/

cd ~/
[ -d ~/termux-metasploit-helper ] && rm -rf ~/termux-metasploit-helper

echo 'Congratulations setup is done...' |lolcat -a

echo 'Now close termux session and reopen ' |lolcat -a

echo 'Type exit and press enter' |lolcat -a



